name: scp copy folder to remote via SSH

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      LOCAL: test
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Copy all files to remote server
        uses: ./
        with:
          local: .
          remote: ndki.loc
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASS_PHRASE }}
          port: ${{ secrets.PORT }}
          dotfiles: true
